// Auto-generates src/data/ticketRegistry.ts from all PDFs in tickets/
const fs = require('fs');
const path = require('path');

const ticketsDir = path.join(__dirname, '..', 'tickets');
const outputFile = path.join(__dirname, '..', 'src', 'data', 'ticketRegistry.ts');

const files = fs.existsSync(ticketsDir)
  ? fs.readdirSync(ticketsDir).filter(f => f.endsWith('.pdf')).sort()
  : [];

const keys = files.map(f => f.replace('.pdf', ''));
const maxLen = keys.reduce((m, k) => Math.max(m, k.length), 0);
const entries = keys
  .map(key => `  '${key}'${' '.repeat(maxLen - key.length)}: require('../../tickets/${key}.pdf'),`)
  .join('\n');

const content = `// AUTO-GENERATED by scripts/generateTicketRegistry.js
// Add a PDF to the tickets/ folder and restart the app — this file updates itself.
// Key format: {city-lowercase}-{yyyy-mm-dd}-{time}  e.g. sevilla-2026-05-28-9am

export const TICKET_ASSETS: Record<string, any> = {
${entries || '  // no tickets yet'}
};

// Converts an activity time string to the ticket filename time key (12-hour format).
// "9:00 AM" → "9am"  |  "12:00 PM" → "12pm"  |  "2:30 PM" → "2_30pm"  |  "7:40 PM" → "7_40pm"
function timeToKey(time: string): string {
  const match = time.match(/(\\d+):(\\d+)\\s*(AM|PM)/i);
  if (!match) return '';
  const h = match[1];
  const m = match[2];
  const ampm = match[3].toLowerCase();
  return m === '00' ? \`\${h}\${ampm}\` : \`\${h}_\${m}\${ampm}\`;
}

// Returns the ticket asset for a given city, date, and activity time, or null if none.
export function getTicket(city: string, date: string, time: string): any | null {
  const key = \`\${city.toLowerCase()}-\${date}-\${timeToKey(time)}\`;
  return TICKET_ASSETS[key] ?? null;
}
`;

fs.writeFileSync(outputFile, content, 'utf8');
console.log(`[gen-tickets] ${files.length} ticket(s) registered: ${keys.join(', ') || 'none'}`);
