// AUTO-GENERATED by scripts/generateTicketRegistry.js
// Add a PDF to the tickets/ folder and restart the app — this file updates itself.
// Key format: {city-lowercase}-{yyyy-mm-dd}-{time}  e.g. sevilla-2026-05-28-9am

export const TICKET_ASSETS: Record<string, any> = {
  'barcelona-2026-05-20-11_30am': require('../../tickets/barcelona-2026-05-20-11_30am.pdf'),
  'barcelona-2026-05-20-11am'   : require('../../tickets/barcelona-2026-05-20-11am.pdf'),
  'barcelona-2026-05-21-11_15am': require('../../tickets/barcelona-2026-05-21-11_15am.pdf'),
  'barcelona-2026-05-21-3_45pm' : require('../../tickets/barcelona-2026-05-21-3_45pm.pdf'),
  'barcelona-2026-05-21-9_15am' : require('../../tickets/barcelona-2026-05-21-9_15am.pdf'),
  'córdoba-2026-05-26-12_48pm'  : require('../../tickets/córdoba-2026-05-26-12_48pm.pdf'),
  'córdoba-2026-05-26-3pm'      : require('../../tickets/córdoba-2026-05-26-3pm.pdf'),
  'granada-2026-05-24-12pm'     : require('../../tickets/granada-2026-05-24-12pm.pdf'),
  'granada-2026-05-24-2_30pm'   : require('../../tickets/granada-2026-05-24-2_30pm.pdf'),
  'granada-2026-05-24-2pm'      : require('../../tickets/granada-2026-05-24-2pm.pdf'),
  'granada-2026-05-24-7_40pm'   : require('../../tickets/granada-2026-05-24-7_40pm.pdf'),
  'granada-2026-05-24-9_30am'   : require('../../tickets/granada-2026-05-24-9_30am.pdf'),
  'madrid-2026-05-30-11am'      : require('../../tickets/madrid-2026-05-30-11am.pdf'),
  'madrid-2026-05-30-7_30am'    : require('../../tickets/madrid-2026-05-30-7_30am.pdf'),
  'madrid-2026-05-31-2_30pm'    : require('../../tickets/madrid-2026-05-31-2_30pm.pdf'),
  'madrid-2026-06-01-9am'       : require('../../tickets/madrid-2026-06-01-9am.pdf'),
  'madrid-2026-06-02-7pm'       : require('../../tickets/madrid-2026-06-02-7pm.pdf'),
  'madrid-2026-06-02-8pm'       : require('../../tickets/madrid-2026-06-02-8pm.pdf'),
  'sevilla-2026-05-27-11_20am'  : require('../../tickets/sevilla-2026-05-27-11_20am.pdf'),
  'sevilla-2026-05-27-12pm'     : require('../../tickets/sevilla-2026-05-27-12pm.pdf'),
  'sevilla-2026-05-27-5_45pm'   : require('../../tickets/sevilla-2026-05-27-5_45pm.pdf'),
  'sevilla-2026-05-27-7pm'      : require('../../tickets/sevilla-2026-05-27-7pm.pdf'),
  'sevilla-2026-05-28-9am'      : require('../../tickets/sevilla-2026-05-28-9am.pdf'),
};

// Converts an activity time string to the ticket filename time key (12-hour format).
// "9:00 AM" → "9am"  |  "12:00 PM" → "12pm"  |  "2:30 PM" → "2_30pm"  |  "7:40 PM" → "7_40pm"
function timeToKey(time: string): string {
  const match = time.match(/(\d+):(\d+)\s*(AM|PM)/i);
  if (!match) return '';
  const h = match[1];
  const m = match[2];
  const ampm = match[3].toLowerCase();
  return m === '00' ? `${h}${ampm}` : `${h}_${m}${ampm}`;
}

// Returns the ticket asset for a given city, date, and activity time, or null if none.
export function getTicket(city: string, date: string, time: string): any | null {
  const key = `${city.toLowerCase()}-${date}-${timeToKey(time)}`;
  return TICKET_ASSETS[key] ?? null;
}
